<?php require 'inc.php';$u=me();if(!$u||$u['role']!='admin'){header('Location: auth.php?m=login');exit;}
if(isset($_GET['backup'])){header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="rallyx-backup-'.date('Y-m-d').'.sqlite"');readfile($dbp);exit;}
if(isset($_GET['members'])){header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="rallyx-members-'.date('Y-m-d').'.csv"');$o=fopen('php://output','w');fputcsv($o,['Name','Email','Role','League','Car','Phone','Joined']);foreach($db->query("SELECT name,email,kind,age_group,car,phone,created FROM users WHERE role!='admin' ORDER BY id")->fetchAll(PDO::FETCH_NUM) as $r)fputcsv($o,array_map(fn($c)=>preg_match('/^[=+\-@]/',(string)$c)?"'".$c:$c,$r));exit;}
$ok=['jpg'=>'image','jpeg'=>'image','png'=>'image','webp'=>'image','mp4'=>'video','mov'=>'video','webm'=>'video'];$msg='';$K=['Driver','Co-driver','Team owner','Mechanic','Marshal','Fan'];
if($_SERVER['REQUEST_METHOD']=='POST'){chk();$a=$_POST['a']??'';
 if($a=='post'&&trim($_POST['title'])){$db->prepare('INSERT INTO posts(title,body) VALUES(?,?)')->execute([trim($_POST['title']),trim($_POST['body'])]);$msg='News published.';}
 if($a=='media'&&isset($_FILES['f'])&&$_FILES['f']['error']===0){$e=strtolower(pathinfo($_FILES['f']['name'],PATHINFO_EXTENSION));
  if(isset($ok[$e])){$p='uploads/files/'.bin2hex(random_bytes(8)).".$e";move_uploaded_file($_FILES['f']['tmp_name'],__DIR__."/$p");$db->prepare('INSERT INTO media(kind,path,caption) VALUES(?,?,?)')->execute([$ok[$e],$p,trim($_POST['cap'])]);$msg='Uploaded.';}else $msg='Use jpg, png, webp, mp4 or webm.';}
 if($a=='banner'){$db->prepare("REPLACE INTO settings(k,v) VALUES('banner',?)")->execute([trim($_POST['b'])]);$msg='Banner saved.';}
 if($a=='event'&&trim($_POST['title'])){$db->prepare('INSERT INTO events(title,day,place) VALUES(?,?,?)')->execute([trim($_POST['title']),$_POST['day'],trim($_POST['place'])]);$msg='Event added.';}
 if($a=='delevent')$db->prepare('DELETE FROM events WHERE id=?')->execute([$_POST['id']]);
 if($a=='edituser'){try{$p=[trim($_POST['name']),strtolower(trim($_POST['email'])),in_array($_POST['kind'],$K)?$_POST['kind']:'Fan',$_POST['age']=='Youth'?'Youth':'Adult',trim($_POST['car']),trim($_POST['phone'])];$q='UPDATE users SET name=?,email=?,kind=?,age_group=?,car=?,phone=? ';if(strlen($_POST['pass'])>=8){$q.=',pass=? ';$p[]=password_hash($_POST['pass'],PASSWORD_DEFAULT);}$p[]=$_POST['id'];$db->prepare($q."WHERE id=? AND role!='admin'")->execute($p);$msg='Member updated.';}catch(Exception $x){$msg='That email is already used.';}}
 if($a=='editmedia'){$db->prepare('UPDATE media SET caption=? WHERE id=?')->execute([trim($_POST['cap']),$_POST['id']]);$msg='Caption saved.';}
 if($a=='restore'||$a=='restoreall'){$have=$db->query('SELECT path FROM media')->fetchAll(PDO::FETCH_COLUMN);foreach(glob(__DIR__.'/uploads/seed/*') as $f){$b=basename($f);if(($a=='restoreall'||$b==($_POST['f']??''))&&!in_array("uploads/seed/$b",$have)){$db->prepare("INSERT INTO media(kind,path,caption) VALUES('image',?,?)")->execute(["uploads/seed/$b",$cap[(int)substr($b,1)-1]??'']);}}$msg='Photos restored.';}
 if($a=='adminpw'&&strlen($_POST['pass'])>=8){$db->prepare("UPDATE users SET pass=? WHERE role='admin'")->execute([password_hash($_POST['pass'],PASSWORD_DEFAULT)]);$msg='Admin password changed.';}
 if($a=='delpost')$db->prepare('DELETE FROM posts WHERE id=?')->execute([$_POST['id']]);
 if($a=='delmedia'){$s=$db->prepare('SELECT path FROM media WHERE id=?');$s->execute([$_POST['id']]);$p=$s->fetchColumn();if($p&&strpos($p,'seed/')===false)@unlink(__DIR__."/$p");$db->prepare('DELETE FROM media WHERE id=?')->execute([$_POST['id']]);}
 if($a=='deluser')$db->prepare("DELETE FROM users WHERE id=? AND role!='admin'")->execute([$_POST['id']]);}
head('Admin | Rally XRC');$T=tok();
function del($a,$id,$T){return "<form method=post class=inl onsubmit=\"return confirm('Delete this?')\"><input type=hidden name=t value=$T><input type=hidden name=a value=$a><input type=hidden name=id value=$id><button class=x>Delete</button></form>";}?>
<main class="wrap"><h2>Admin panel</h2><?php if($msg)echo '<p class="err">'.h($msg).'</p>';?>
<div id="dz" tabindex="0">Drop videos or photos here, or click to choose</div><input type="file" id="fi" multiple accept="image/*,video/*" hidden><p id="st"></p>
<script>const dz=document.getElementById('dz'),fi=document.getElementById('fi'),st=document.getElementById('st');
async function up(fs){let ok=0;for(const f of fs){st.textContent='Uploading '+f.name+'...';const d=new FormData();d.append('t','<?=$T?>');d.append('a','media');d.append('cap',f.name.replace(/\.[^.]+$/,''));d.append('f',f);
try{const r=await fetch('admin.php',{method:'POST',body:d}),x=await r.text();if(x.includes('Uploaded.'))ok++;else{st.textContent='Could not upload '+f.name+'. Use mp4, mov, webm, jpg or png, and check the server upload limit.';return}}catch(e){st.textContent='Upload failed for '+f.name;return}}
if(ok)location.reload()}
dz.ondragover=e=>{e.preventDefault();dz.classList.add('on')};dz.ondragleave=()=>dz.classList.remove('on');dz.ondrop=e=>{e.preventDefault();up(e.dataTransfer.files)};dz.onclick=()=>fi.click();fi.onchange=()=>up(fi.files);</script>
<div class="grid"><?php $c=fn($q)=>$db->query($q)->fetchColumn();foreach([['Members',"SELECT COUNT(*) FROM users WHERE role!='admin'"],['Youth',"SELECT COUNT(*) FROM users WHERE age_group='Youth'"],['Adult',"SELECT COUNT(*) FROM users WHERE age_group='Adult'"],['Photos',"SELECT COUNT(*) FROM media WHERE kind='image'"],['Videos',"SELECT COUNT(*) FROM media WHERE kind='video'"],['News posts','SELECT COUNT(*) FROM posts']] as $s)echo '<div class="mem"><b>'.$c($s[1]).'</b>'.$s[0].'</div>';?></div><br>
<div class="split2"><form method="post"><h3>Post news</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="post"><label>Title<input name="title" required></label><label>Message<textarea name="body" rows="5"></textarea></label><button class="btn">Publish news</button></form>
<form method="post" enctype="multipart/form-data"><h3>Add photo or video</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="media"><label>File<input type="file" name="f" accept="image/*,video/mp4,video/webm" required></label><label>Caption<input name="cap"></label><button class="btn">Upload</button></form></div>
<div class="split2"><form method="post"><h3>Site banner</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="banner"><label>Announcement (empty removes it)<input name="b" value="<?=h($db->query("SELECT v FROM settings WHERE k='banner'")->fetchColumn())?>"></label><button class="btn">Save banner</button></form>
<form method="post"><h3>Add event</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="event"><label>Event name<input name="title" required></label><label>Date<input type="date" name="day" required></label><label>Place<input name="place"></label><button class="btn">Add event</button></form></div>
<h3>Events</h3><?php foreach($db->query('SELECT id,title,day FROM events ORDER BY day') as $r)echo '<p>'.h($r['title']).', '.h($r['day']).' '.del('delevent',$r['id'],$T).'</p>';?>
<h3>News</h3><?php foreach($db->query('SELECT id,title FROM posts ORDER BY id DESC') as $r)echo '<p>'.h($r['title']).' '.del('delpost',$r['id'],$T).'</p>';?>
<h3>Media</h3><div class="grid"><?php foreach($db->query('SELECT * FROM media ORDER BY id DESC') as $r)echo '<div class="mem">'.($r['kind']=='image'?'<img src="'.h($r['path']).'" alt="">':'<video src="'.h($r['path']).'"></video>').'<form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="editmedia"><input type="hidden" name="id" value="'.$r['id'].'"><input name="cap" value="'.h($r['caption']).'" aria-label="Caption"><button class="x">Save caption</button></form>'.del('delmedia',$r['id'],$T).'</div>';?></div>
<?php $have=$db->query("SELECT path FROM media")->fetchAll(PDO::FETCH_COLUMN);$gone=array_filter(glob(__DIR__.'/uploads/seed/*'),fn($f)=>!in_array('uploads/seed/'.basename($f),$have));?>
<h3>Deleted original photos</h3><?php if(!$gone)echo '<p>Nothing to restore.</p>';else{?><div class="grid"><?php foreach($gone as $f){$b=basename($f);echo '<div class="mem"><img src="uploads/seed/'.h($b).'" alt=""><p>'.h($cap[(int)substr($b,1)-1]??'').'</p><form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="restore"><input type="hidden" name="f" value="'.h($b).'"><button class="btn">Restore</button></form></div>';}?></div><br><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="restoreall"><button class="btn">Restore all</button></form><?php }?>
<h3>Members</h3><?php foreach($db->query("SELECT * FROM users WHERE role!='admin' ORDER BY id DESC") as $r){echo '<details><summary>'.h($r['name']).', '.h($r['kind']).', '.h($r['age_group']).'</summary><form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="edituser"><input type="hidden" name="id" value="'.$r['id'].'"><label>Name<input name="name" value="'.h($r['name']).'" required></label><label>Email<input type="email" name="email" value="'.h($r['email']).'" required></label><label>Role<select name="kind">';foreach($K as $k)echo '<option'.($k==$r['kind']?' selected':'').'>'.$k.'</option>';echo '</select></label><label>League<select name="age"><option'.($r['age_group']=='Youth'?' selected':'').'>Youth</option><option'.($r['age_group']=='Adult'?' selected':'').'>Adult</option></select></label><label>Car or team<input name="car" value="'.h($r['car']).'"></label><label>Phone<input name="phone" value="'.h($r['phone']).'"></label><label>New password (empty keeps current)<input type="password" name="pass" minlength="8"></label><button class="btn">Save changes</button></form>'.del('deluser',$r['id'],$T).'</details>';}?><h3>Backups</h3><p><a class="btn" href="admin.php?backup=1">Download database backup</a> <a class="btn alt" href="admin.php?members=1">Download members list (CSV)</a></p><h3>Admin account</h3><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="adminpw"><label>New admin password (8+ characters)<input type="password" name="pass" minlength="8" required></label><button class="btn">Change password</button></form></main><?php foot();
