<?php require 'inc.php';$u=me();if(!$u||$u['role']!='admin'){header('Location: auth.php?m=login');exit;}
if(isset($_GET['backup'])){header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="rallyx-backup-'.date('Y-m-d').'.sqlite"');readfile($dbp);exit;}
if(isset($_GET['members'])){header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="rallyx-members-'.date('Y-m-d').'.csv"');$o=fopen('php://output','w');fcsv($o,['Name','Email','Role','League','Team','Car type','Inspired by','Phone','Joined']);foreach($db->query("SELECT name,email,kind,age_group,team,car_type,inspired,phone,created FROM users WHERE role!='admin' ORDER BY id")->fetchAll(PDO::FETCH_NUM) as $r)fcsv($o,array_map(fn($c)=>(preg_match('/^[=+\-@]/',(string)$c)&&!preg_match('/^\+\d{8,15}$/',(string)$c))?"'".$c:$c,$r));exit;}
$ok=['jpg'=>'image','jpeg'=>'image','png'=>'image','webp'=>'image','mp4'=>'video','mov'=>'video','m4v'=>'video','webm'=>'video'];$msg='';$K=['Driver','Co-driver','Team owner','Mechanic','Marshal','Fan'];
$ajax=($_SERVER['HTTP_X_REQUESTED_WITH']??'')=='fetch';
function jout($ok,$m){header('Content-Type: application/json');echo json_encode(['ok'=>$ok,'msg'=>$m]);exit;}
if($_SERVER['REQUEST_METHOD']=='POST'&&$ajax&&empty($_POST)&&empty($_FILES))jout(false,'This file is bigger than the server limit.');
if($_SERVER['REQUEST_METHOD']=='POST'){chk();$a=$_POST['a']??'';
 if($a=='post'&&trim($_POST['title'])){$db->prepare('INSERT INTO posts(title,body) VALUES(?,?)')->execute([trim($_POST['title']),trim($_POST['body'])]);$msg='News published.';if(!empty($_POST['notify'])){require_once 'push.php';[$sn]=push_all(trim($_POST['title']),mb_strimwidth(trim($_POST['body']),0,120,'...'),'/#news');$msg.=' Notification sent to '.$sn.' device'.($sn==1?'':'s').'.';}}
 if($a=='media'){$f=$_FILES['f']??null;$er=$f['error']??4;$e=strtolower(pathinfo($f['name']??'',PATHINFO_EXTENSION));
  if($er!==0)$msg=[1=>'File is bigger than the server limit.',2=>'File is bigger than the server limit.',3=>'Upload was interrupted. Try again.',4=>'No file was chosen.'][$er]??'Upload failed.';
  elseif(!isset($ok[$e]))$msg='Cannot use .'.$e.' files. Use mp4, mov, m4v, webm, jpg, png or webp.';
  elseif(!is_dir(__DIR__.'/uploads/files')||!move_uploaded_file($f['tmp_name'],__DIR__.'/'.($p='uploads/files/'.bin2hex(random_bytes(8)).".$e")))$msg='The server could not save the file (storage may be full).';
  else{$db->prepare('INSERT INTO media(kind,path,caption,sort) VALUES(?,?,?,(SELECT COALESCE(MAX(sort),0)+1 FROM media))')->execute([$ok[$e],$p,trim($_POST['cap']??'')]);$msg='Uploaded.';$good=1;}
  if($ajax)jout(!empty($good),$msg);}
 if($a=='banner'){$db->prepare("REPLACE INTO settings(k,v) VALUES('banner',?)")->execute([trim($_POST['b'])]);$msg='Banner saved.';}
 if($a=='event'&&trim($_POST['title'])){$db->prepare('INSERT INTO events(title,day,place) VALUES(?,?,?)')->execute([trim($_POST['title']),$_POST['day'],trim($_POST['place'])]);$msg='Event added.';}
 if($a=='delevent')$db->prepare('DELETE FROM events WHERE id=?')->execute([$_POST['id']]);
 if($a=='edituser'){try{$p=[trim($_POST['name']),strtolower(trim($_POST['email'])),in_array($_POST['kind'],$K)?$_POST['kind']:'Fan',$_POST['age']=='Junior'?'Junior':'Senior',trim($_POST['team']??''),trim($_POST['car_type']??''),trim($_POST['inspired']??''),trim($_POST['phone'])];$q='UPDATE users SET name=?,email=?,kind=?,age_group=?,team=?,car_type=?,inspired=?,phone=? ';if(strlen($_POST['pass'])>=8){$q.=',pass=? ';$p[]=password_hash($_POST['pass'],PASSWORD_DEFAULT);}$p[]=$_POST['id'];$db->prepare($q."WHERE id=? AND role!='admin'")->execute($p);$msg='Member updated.';}catch(Exception $x){$msg='That email is already used.';}}
 if($a=='editmedia'){$db->prepare('UPDATE media SET caption=? WHERE id=?')->execute([trim($_POST['cap']),$_POST['id']]);$msg='Caption saved.';}
 if($a=='restore'||$a=='restoreall'){$have=$db->query('SELECT path FROM media')->fetchAll(PDO::FETCH_COLUMN);foreach(glob(__DIR__.'/uploads/seed/*.{jpg,jpeg,png,webp}',GLOB_BRACE) as $f){$b=basename($f);if(($a=='restoreall'||$b==($_POST['f']??''))&&!in_array("uploads/seed/$b",$have)){$db->prepare("INSERT INTO media(kind,path,caption,sort) VALUES('image',?,?,(SELECT COALESCE(MAX(sort),0)+1 FROM media))")->execute(["uploads/seed/$b",$cap[(int)substr($b,1)-1]??'']);}}$msg='Photos restored.';}
 if($a=='adminpw'&&strlen($_POST['pass'])>=8){$db->prepare("UPDATE users SET pass=? WHERE role='admin'")->execute([password_hash($_POST['pass'],PASSWORD_DEFAULT)]);$msg='Admin password changed.';}
 if($a=='setcover'){$db->prepare("REPLACE INTO settings(k,v) VALUES('hero_media',?)")->execute([(int)$_POST['id']]);$msg='Cover video set. It now plays on the home page.';}
 if($a=='cover'){foreach(['hero_title'=>'ht','hero_sub'=>'hs','hero_btn'=>'hb'] as $k=>$f)$db->prepare('REPLACE INTO settings(k,v) VALUES(?,?)')->execute([$k,trim($_POST[$f]??'')]);$mid=(int)($_POST['hm']??0);if($mid)$db->prepare('REPLACE INTO settings(k,v) VALUES(?,?)')->execute(['hero_media',$mid]);else $db->exec("DELETE FROM settings WHERE k='hero_media'");$msg='Cover saved.';}
 if($a=='clearcover'){$db->prepare("DELETE FROM settings WHERE k='hero_media'")->execute();$msg='The cover is the photo again.';}
 if($a=='reorder'){$ids=array_filter(array_map('intval',explode(',',$_POST['ids']??'')));$st=$db->prepare('UPDATE media SET sort=? WHERE id=?');$n=0;foreach($ids as $i)$st->execute([++$n,$i]);if($ajax)jout(true,'Order saved.');$msg='Order saved.';}
 if($a=='togglefeat'){$db->prepare('UPDATE media SET featured=CASE WHEN COALESCE(featured,0)=1 THEN 0 ELSE 1 END WHERE id=?')->execute([(int)($_POST['id']??0)]);$msg='Home page selection updated.';}
 if($a=='addsponsor'){$f=$_FILES['logo']??null;$im=($f&&$f['error']===0&&$f['size']<=5*1048576)?@getimagesize($f['tmp_name']):false;$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$im['mime']??'']??'';$nm=trim($_POST['name']??'');
  if(!$ext||!$nm)$msg='Please enter a name and choose a JPG, PNG or WebP logo under 5 MB.';
  else{$p='uploads/files/sp'.bin2hex(random_bytes(6)).'.'.$ext;if(is_dir(__DIR__.'/uploads/files')&&move_uploaded_file($f['tmp_name'],__DIR__.'/'.$p)){$u=trim($_POST['url']??'');$db->prepare('INSERT INTO sponsors(name,logo,url,sort) VALUES(?,?,?,(SELECT COALESCE(MAX(sort),0)+1 FROM sponsors))')->execute([$nm,$p,preg_match('#^https?://#i',$u)?$u:'']);$msg='Sponsor added.';}else $msg='The server could not save the logo.';}}
 if($a=='editsponsor'){$u=trim($_POST['url']??'');$db->prepare('UPDATE sponsors SET name=?,url=? WHERE id=?')->execute([trim($_POST['name']??''),preg_match('#^https?://#i',$u)?$u:'',(int)($_POST['id']??0)]);$msg='Sponsor saved.';}
 if($a=='delsponsor'){$s=$db->prepare('SELECT logo FROM sponsors WHERE id=?');$s->execute([(int)($_POST['id']??0)]);$lg=$s->fetchColumn();if($lg&&strpos($lg,'uploads/files/sp')===0)@unlink(__DIR__.'/'.$lg);$db->prepare('DELETE FROM sponsors WHERE id=?')->execute([(int)($_POST['id']??0)]);$msg='Sponsors updated.';}
 if($a=='movesponsor'){$ids=array_map('intval',$db->query('SELECT id FROM sponsors ORDER BY sort,id')->fetchAll(PDO::FETCH_COLUMN));$i=array_search((int)($_POST['id']??0),$ids,true);$j=($i===false)?-1:$i+((int)($_POST['d']??0)<0?-1:1);if($i!==false&&isset($ids[$j])){[$ids[$i],$ids[$j]]=[$ids[$j],$ids[$i]];$st=$db->prepare('UPDATE sponsors SET sort=? WHERE id=?');foreach($ids as $k=>$x)$st->execute([$k+1,$x]);}$msg='Sponsors updated.';}
 if($a=='delpost')$db->prepare('DELETE FROM posts WHERE id=?')->execute([$_POST['id']]);
 if($a=='delmedia'){$s=$db->prepare('SELECT path FROM media WHERE id=?');$s->execute([$_POST['id']]);$p=$s->fetchColumn();if($p&&strpos($p,'seed/')===false)@unlink(__DIR__."/$p");$db->prepare('DELETE FROM media WHERE id=?')->execute([$_POST['id']]);}
 if($a=='deluser')$db->prepare("DELETE FROM users WHERE id=? AND role!='admin'")->execute([$_POST['id']]);}
head('Admin | Rally XRC');$T=tok();
function del($a,$id,$T){return "<form method=post class=inl onsubmit=\"return confirm('Delete this?')\"><input type=hidden name=t value=$T><input type=hidden name=a value=$a><input type=hidden name=id value=$id><button class=x>Delete</button></form>";}?>
<main class="wrap"><h2>Admin panel</h2><p><a class="btn alt" href="notify.php">Send a notification</a> <a class="btn alt" href="payments.php">Payments</a></p><?php if($msg)echo '<p class="err">'.h($msg).'</p>';?>
<div id="dz" tabindex="0">Drop videos or photos here, or click to choose (mp4, mov, webm, jpg, png, up to 500 MB each)</div><input type="file" id="fi" multiple accept="image/*,video/*" hidden><p id="st"></p>
<script>const dz=document.getElementById('dz'),fi=document.getElementById('fi'),st=document.getElementById('st'),OK=/\.(mp4|mov|m4v|webm|jpe?g|png|webp)$/i,MAX=500*1024*1024;
function row(t){const p=document.createElement('p');p.textContent=t;st.appendChild(p);return p}
function bad(r,t){r.textContent=t;r.style.color='#c4421a'}
function send(f,r){return new Promise(res=>{const d=new FormData();d.append('t','<?=$T?>');d.append('a','media');d.append('cap',f.name.replace(/\.[^.]+$/,''));d.append('f',f);const x=new XMLHttpRequest();x.open('POST','admin.php');x.setRequestHeader('X-Requested-With','fetch');
x.upload.onprogress=e=>{if(e.lengthComputable)r.textContent=f.name+': uploading '+Math.round(e.loaded/e.total*100)+'%'};
x.onload=()=>{let j;try{j=JSON.parse(x.responseText)}catch(e){j={ok:false,msg:'The server did not accept it. Reload the page and log in again, or the file may be too big.'}}if(j.ok)r.textContent=f.name+': done';else bad(r,f.name+': FAILED. '+j.msg);res(j.ok)};
x.onerror=()=>{bad(r,f.name+': FAILED. Network problem, try again.');res(false)};x.send(d)})}
async function up(fs){st.textContent='';let ok=0,ng=0;for(const f of fs){const r=row(f.name+': waiting');
if(!OK.test(f.name)){bad(r,f.name+': FAILED. Use mp4, mov, m4v, webm, jpg, png or webp.');ng++;continue}
if(f.size>MAX){bad(r,f.name+': FAILED. Over 500 MB. Shrink it first.');ng++;continue}
(await send(f,r))?ok++:ng++}
row(ok+' uploaded, '+ng+' failed.');if(ok&&!ng)setTimeout(()=>location.reload(),1200);else if(ok)row('Reload the page to see the files that uploaded.')}
dz.ondragover=e=>{e.preventDefault();dz.classList.add('on')};dz.ondragleave=()=>dz.classList.remove('on');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('on');up(e.dataTransfer.files)};dz.onclick=()=>fi.click();fi.onchange=()=>up(fi.files);</script>
<div class="grid"><?php $c=fn($q)=>$db->query($q)->fetchColumn();foreach([['Members',"SELECT COUNT(*) FROM users WHERE role!='admin'"],['Junior',"SELECT COUNT(*) FROM users WHERE age_group='Junior'"],['Senior',"SELECT COUNT(*) FROM users WHERE age_group='Senior'"],['Photos',"SELECT COUNT(*) FROM media WHERE kind='image'"],['Videos',"SELECT COUNT(*) FROM media WHERE kind='video'"],['News posts','SELECT COUNT(*) FROM posts']] as $s)echo '<div class="mem"><b>'.$c($s[1]).'</b>'.$s[0].'</div>';?></div><br>
<div class="split2"><form method="post"><h3>Post news</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="post"><label>Title<input name="title" required></label><label>Message<textarea name="body" rows="5"></textarea></label><label><input type="checkbox" name="notify" value="1" style="display:inline;width:auto"> Also send this as a notification to members</label><button class="btn">Publish news</button></form>
<form method="post" enctype="multipart/form-data"><h3>Add photo or video</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="media"><label>File<input type="file" name="f" accept="image/*,video/mp4,video/webm" required></label><label>Caption<input name="cap"></label><button class="btn">Upload</button></form></div>
<div class="split2"><form method="post"><h3>Site banner</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="banner"><label>Announcement (empty removes it)<input name="b" value="<?=h($db->query("SELECT v FROM settings WHERE k='banner'")->fetchColumn())?>"></label><button class="btn">Save banner</button></form>
<form method="post"><h3>Add event</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="event"><label>Event name<input name="title" required></label><label>Date<input type="date" name="day" required></label><label>Place<input name="place"></label><button class="btn">Add event</button></form></div>
<h3>Events</h3><?php foreach($db->query('SELECT id,title,day FROM events ORDER BY day') as $r)echo '<p>'.h($r['title']).', '.h($r['day']).' '.del('delevent',$r['id'],$T).'</p>';?>
<h3>News</h3><?php foreach($db->query('SELECT id,title FROM posts ORDER BY id DESC') as $r)echo '<p>'.h($r['title']).' '.del('delpost',$r['id'],$T).'</p>';?>
<h3>Media</h3><?php $fi=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='image' AND featured=1")->fetchColumn();$fv=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='video' AND featured=1")->fetchColumn();?><p>The home page shows up to <b>7 photos</b> and <b>3 videos</b>. Click <b>&#9734; Show on home page</b> under the ones you want there (chosen so far: <?=$fi?> photo<?=$fi==1?'':'s'?>, <?=$fv?> video<?=$fv==1?'':'s'?>)<?=($fi>7||$fv>3)?'. Only the first 7 photos and 3 videos in your order are shown':''?>. If you choose none, the first ones in your order are shown. Everything else is on the <a href="gallery.php">All photos and videos</a> page.</p><div class="grid" id="mg"><?php foreach($db->query('SELECT * FROM media ORDER BY sort,id') as $r)echo '<div class="mem" draggable="true" data-id="'.$r['id'].'"><p><button type="button" class="x" data-mv="-1">&#9664; Earlier</button> <button type="button" class="x" data-mv="1">Later &#9654;</button></p>'.($r['kind']=='image'?'<img src="'.h($r['path']).'" alt="">':'<video muted playsinline preload="metadata" src="'.h(mv($r['path'])).'#t=0.1"></video>').'<form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="editmedia"><input type="hidden" name="id" value="'.$r['id'].'"><input name="cap" value="'.h($r['caption']).'" aria-label="Caption"><button class="x">Save caption</button></form>'.(1?'<form method="post" class="inl"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="setcover"><input type="hidden" name="id" value="'.$r['id'].'"><button class="btn">Use as cover</button></form> ':'').'<form method="post" class="inl"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="togglefeat"><input type="hidden" name="id" value="'.$r['id'].'"><button class="x">'.($r['featured']?'&#9733; On home page (remove)':'&#9734; Show on home page').'</button></form> '.del('delmedia',$r['id'],$T).'</div>';?></div>
<?php $have=$db->query("SELECT path FROM media")->fetchAll(PDO::FETCH_COLUMN);$gone=array_filter(glob(__DIR__.'/uploads/seed/*.{jpg,jpeg,png,webp}',GLOB_BRACE),fn($f)=>!in_array('uploads/seed/'.basename($f),$have));?>
<h3>Deleted original photos</h3><?php if(!$gone)echo '<p>Nothing to restore.</p>';else{?><div class="grid"><?php foreach($gone as $f){$b=basename($f);echo '<div class="mem"><img src="uploads/seed/'.h($b).'" alt=""><p>'.h($cap[(int)substr($b,1)-1]??'').'</p><form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="restore"><input type="hidden" name="f" value="'.h($b).'"><button class="btn">Restore</button></form></div>';}?></div><br><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="restoreall"><button class="btn">Restore all</button></form><?php }?>
<h3>Members</h3><?php foreach($db->query("SELECT * FROM users WHERE role!='admin' ORDER BY id DESC") as $r){echo '<details><summary>'.h($r['name']).', '.h($r['kind']).', '.h($r['age_group']).'</summary>'.($r['photo']?'<img class="pp" src="'.h($r['photo']).'" alt="Member photo">':'').'<form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="edituser"><input type="hidden" name="id" value="'.$r['id'].'"><label>Name<input name="name" value="'.h($r['name']).'" required></label><label>Email<input type="email" name="email" value="'.h($r['email']).'" required></label><label>Role<select name="kind">';foreach($K as $k)echo '<option'.($k==$r['kind']?' selected':'').'>'.$k.'</option>';echo '</select></label><label>League<select name="age"><option'.($r['age_group']=='Junior'?' selected':'').'>Junior</option><option'.($r['age_group']=='Senior'?' selected':'').'>Senior</option></select></label><label>Team<input name="team" value="'.h($r['team']).'"></label><label>Car type<input name="car_type" value="'.h($r['car_type']).'"></label><label>Inspired by<input name="inspired" value="'.h($r['inspired']).'"></label><label>Phone<input name="phone" value="'.h($r['phone']).'"></label><label>New password (empty keeps current)<input type="password" name="pass" minlength="8"></label><button class="btn">Save changes</button></form>'.del('deluser',$r['id'],$T).'</details>';}?><h3>Cover page</h3><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="cover">
<label>Headline (one line per row)<textarea name="ht" rows="3"><?=h(setting('hero_title',"Every driver.\nOne stage.\nRally XRC."))?></textarea></label>
<label>Short text under the headline<textarea name="hs" rows="3"><?=h(setting('hero_sub','The official RC rally game of Uganda. Register your car, find your rivals and race on the dirt, from first-time juniors to veteran drivers.'))?></textarea></label>
<label>Main button text<input name="hb" value="<?=h(setting('hero_btn','Register now'))?>"></label>
<label>Cover photo or video<select name="hm"><option value="0">Default cover (the cover video)</option><?php foreach($db->query('SELECT id,kind,caption FROM media ORDER BY kind DESC,id DESC') as $r)echo '<option value="'.$r['id'].'"'.($r['id']==setting('hero_media')?' selected':'').'>'.($r['kind']=='video'?'Video: ':'Photo: ').h($r['caption']?:'untitled '.$r['id']).'</option>';?></select></label>
<button class="btn">Save cover</button></form><p>Add new photos or videos with the drop box above, then choose them here. You can also click <b>Use as cover</b> under any photo or video in the media list.</p>
<h3>Sponsors (shown at the bottom of the site)</h3>
<?php $spn=$db->query('SELECT * FROM sponsors ORDER BY sort,id')->fetchAll(PDO::FETCH_ASSOC);$mvb=fn($d,$id)=>'<form method="post" class="inl"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="movesponsor"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="d" value="'.$d.'"><button class="x">'.($d<0?'&#9664; Earlier':'Later &#9654;').'</button></form> ';
if(!$spn)echo '<p>No sponsors yet.</p>';
echo '<div class="grid">';foreach($spn as $s)echo '<div class="mem"><img class="slogo" src="'.h($s['logo']).'" alt=""><form method="post"><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="editsponsor"><input type="hidden" name="id" value="'.$s['id'].'"><label>Name<input name="name" value="'.h($s['name']).'" required></label><label>Website (optional, starts with https://)<input name="url" value="'.h($s['url']).'"></label><button class="btn">Save</button></form><p>'.$mvb(-1,$s['id']).$mvb(1,$s['id']).del('delsponsor',$s['id'],$T).'</p></div>';echo '</div>';?>
<form method="post" enctype="multipart/form-data"><h3>Add a sponsor</h3><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="addsponsor"><label>Sponsor name<input name="name" required></label><label>Website (optional, starts with https://)<input name="url"></label><label>Logo (JPG, PNG or WebP)<input type="file" name="logo" accept="image/*" required></label><button class="btn">Add sponsor</button></form>
<h3>Backups</h3><p><a class="btn" href="admin.php?backup=1">Download database backup</a> <a class="btn alt" href="admin.php?members=1">Download members list (CSV)</a></p><h3>Admin account</h3><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="adminpw"><label>New admin password (8+ characters)<input type="password" name="pass" minlength="8" required></label><button class="btn">Change password</button></form><script>(function(){const K='rxdraft:',p=sessionStorage.getItem('rxp'),ok=/saved|published|added|updated|uploaded|changed|restored|confirmed|set\./i.test((document.querySelector('.err')||{}).textContent||'');
if(ok||!p){Object.keys(localStorage).filter(k=>k.startsWith(K)).forEach(k=>localStorage.removeItem(k));sessionStorage.removeItem('rxp')}
const fs=[...document.querySelectorAll('main form')];fs.forEach((f,i)=>{f.querySelectorAll('input:not([type=hidden]):not([type=file]):not([type=password]),textarea').forEach(el=>{if(!el.name)return;const k=K+i+':'+el.name,v=localStorage.getItem(k);if(v!==null&&v!=='')el.value=v;el.addEventListener('input',()=>localStorage.setItem(k,el.value))});f.addEventListener('submit',()=>sessionStorage.setItem('rxp','1'))})})()</script>
<script>(function(){const y=sessionStorage.getItem('rxy');if(y!==null){sessionStorage.removeItem('rxy');scrollTo(0,+y)}
document.addEventListener('submit',e=>{if(!e.defaultPrevented)sessionStorage.setItem('rxy',scrollY)});
const g=document.getElementById('mg');if(!g)return;let dr=null;const T=document.querySelector('input[name=t]').value;
function save(){const d=new FormData();d.append('t',T);d.append('a','reorder');d.append('ids',[...g.children].map(c=>c.dataset.id).join(','));const x=new XMLHttpRequest();x.open('POST','admin.php');x.setRequestHeader('X-Requested-With','fetch');x.send(d)}
g.addEventListener('dragstart',e=>{dr=e.target.closest('.mem');if(dr)dr.style.opacity='.4'});g.addEventListener('dragend',()=>{if(dr)dr.style.opacity='';dr=null});
g.addEventListener('dragover',e=>{e.preventDefault();const t=e.target.closest('.mem');if(!dr||!t||t===dr)return;const r=t.getBoundingClientRect();g.insertBefore(dr,(e.clientX-r.left)>r.width/2?t.nextSibling:t)});
g.addEventListener('drop',e=>{e.preventDefault();save()});
g.addEventListener('click',e=>{const b=e.target.closest('[data-mv]');if(!b)return;const c=b.closest('.mem'),d=+b.dataset.mv;if(d<0&&c.previousElementSibling)g.insertBefore(c,c.previousElementSibling);if(d>0&&c.nextElementSibling)g.insertBefore(c.nextElementSibling,c);save();c.scrollIntoView({block:'nearest'})})})()</script>
</main><?php foot();
