<?php require 'inc.php';head('Rally XRC Uganda | Official RC rally racing');
$hero=basename((glob(__DIR__.'/uploads/seed/s12.*')?:[''])[0]);
$poster=is_file(__DIR__.'/uploads/cover.jpg')?'uploads/cover.jpg':'uploads/seed/'.$hero;
$hm=$db->query("SELECT m.kind,m.path FROM settings s JOIN media m ON m.id=CAST(s.v AS INTEGER) WHERE s.k='hero_media'")->fetch(PDO::FETCH_ASSOC);
$hv=($hm&&$hm['kind']=='video')?$hm['path']:'';$bgimg=($hm&&$hm['kind']=='image')?$hm['path']:$poster;
$me=me();
$posts=$db->query('SELECT * FROM posts ORDER BY id DESC LIMIT 6')->fetchAll();
$mem=$db->query("SELECT id,name,kind,age_group,car,photo FROM users WHERE role!='admin' ORDER BY id DESC")->fetchAll();
$img=$db->query("SELECT * FROM media WHERE kind='image' ORDER BY sort,id")->fetchAll();
$vid=$db->query("SELECT * FROM media WHERE kind='video' ORDER BY sort,id")->fetchAll();?>
<header class="hero<?=$hv?' hasv':''?>"><?php if($hv):?><video class="hv" autoplay muted loop playsinline preload="auto" poster="<?=h($poster)?>" src="<?=h(mv($hv))?>"></video><div class="bg"></div><?php else:?><div class="bg" style="background-image:url(<?=h($bgimg)?>)"></div><?php endif;?><div class="wrap"><h1><?=nl2br(h(setting('hero_title',"Every driver.\nOne stage.\nRally XRC.")))?></h1><p><?=h(setting('hero_sub','The official RC rally game of Uganda. Register your car, find your rivals and race on the dirt, from first-time juniors to veteran drivers.'))?></p><a class="btn" href="auth.php?m=register"><?=h(setting('hero_btn','Register now'))?></a> <a class="btn alt" href="#gallery">See the action</a></div>
<svg viewBox="0 0 600 60" preserveAspectRatio="none"><path d="M0 40 C100 5 160 60 260 30 S420 5 600 35" /></svg></header>
<section id="news" class="wrap"><h2>Latest news</h2><?php foreach($posts as $p):?><details open><summary><?=h($p['title'])?> <small><?=h(substr($p['created'],0,10))?></small></summary><p><?=nl2br(h($p['body']))?></p></details><?php endforeach;?></section>
<section id="leagues" class="split"><div class="junior"><h2>Junior league</h2><p>Under 18? Bring a car, learn stage craft and race alongside friends. Mechanics and marshals are welcome too.</p><a class="btn" href="auth.php?m=register&age=Junior">Join as junior</a></div><div class="senior"><h2>Senior league</h2><p>Teams, sponsors and seasoned drivers compete for the top step. Link your team and show your livery.</p><a class="btn" href="auth.php?m=register&age=Senior">Join as senior</a></div></section>
<section id="events" class="wrap"><h2>Events</h2><div class="grid"><?php $n=0;foreach($db->query('SELECT * FROM events ORDER BY day') as $e){$n++;echo '<div class="mem"><h3>'.h($e['title']).'</h3><p>'.h($e['day']).($e['place']?', '.h($e['place']):'').'</p></div>';}if(!$n)echo '<p>No events yet. Check back soon.</p>';?></div></section>
<section id="drivers" class="wrap"><h2>The grid</h2><?php if(!$mem)echo '<p>No members yet. Be the first on the grid.</p>';?><div class="grid"><?php foreach($mem as $m):?><div class="mem"><?php if(!empty($m['photo'])&&$me&&($me['role']=='admin'||$me['id']==$m['id']))echo '<img class="av" src="'.h($m['photo']).'" alt="">';?><h3><?=h($m['name'])?></h3><p><?=h($m['kind'])?>, <?=h($m['age_group'])?><?=$m['car']?'. Car: '.h($m['car']):''?></p></div><?php endforeach;?></div></section>
<section id="gallery" class="wrap"><h2>Gallery</h2><div class="masonry"><?php foreach($img as $i):?><figure><img loading="lazy" src="<?=h($i['path'])?>" alt="<?=h($i['caption'])?>"><figcaption><?=h($i['caption'])?></figcaption></figure><?php endforeach;?></div></section>
<section id="videos" class="wrap"><h2>Videos</h2><?php if(!$vid)echo '<p>Race videos will appear here once the admin uploads them.</p>';?><div class="vgrid"><?php foreach($vid as $v):?><figure class="vid" data-src="<?=h(mv($v['path']))?>"><video muted playsinline preload="metadata" src="<?=h(mv($v['path']))?>#t=0.1"></video><figcaption><?=h($v['caption'])?></figcaption></figure><?php endforeach;?></div></section>
<script>const hv=document.querySelector('.hv');if(hv&&(matchMedia('(prefers-reduced-motion:reduce)').matches||(navigator.connection&&navigator.connection.saveData))){const hd=hv.parentNode;hd.style.background='url('+hv.poster+') center/cover';hv.remove()}</script>
<?php foot();
