<?php require 'inc.php';head('Rally XRC Uganda | Official RC rally racing');
$hero=basename((glob(__DIR__.'/uploads/seed/s12.*')?:[''])[0]);
$poster=is_file(__DIR__.'/uploads/cover.jpg')?'uploads/cover.jpg':'uploads/seed/'.$hero;
$hm=$db->query("SELECT m.kind,m.path FROM settings s JOIN media m ON m.id=CAST(s.v AS INTEGER) WHERE s.k='hero_media'")->fetch(PDO::FETCH_ASSOC);
$hv=($hm&&$hm['kind']=='video')?$hm['path']:'';$bgimg=($hm&&$hm['kind']=='image')?$hm['path']:$poster;
if(!$hm&&is_file(__DIR__.'/uploads/cover.mp4'))$hv='uploads/cover.mp4';
$me=me();
$posts=$db->query('SELECT * FROM posts ORDER BY id DESC LIMIT 6')->fetchAll();
$mem=$db->query("SELECT id,name,kind,age_group,team,car_type,photo,show_photo,car_photo FROM users WHERE role!='admin' ORDER BY id DESC")->fetchAll();
$ni=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='image'")->fetchColumn();$nv=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='video'")->fetchColumn();
$fi=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='image' AND featured=1")->fetchColumn();$fv=(int)$db->query("SELECT COUNT(*) FROM media WHERE kind='video' AND featured=1")->fetchColumn();
$img=$db->query("SELECT * FROM media WHERE kind='image'".($fi?" AND featured=1":"")." ORDER BY sort,id LIMIT 7")->fetchAll();
$vid=$db->query("SELECT * FROM media WHERE kind='video'".($fv?" AND featured=1":"")." ORDER BY sort,id LIMIT 3")->fetchAll();?>
<?php $circ=$db->query("SELECT path,caption FROM media WHERE kind='image' AND circle=1 ORDER BY sort,id LIMIT 6")->fetchAll();if(!$circ)$circ=$db->query("SELECT path,caption FROM media WHERE kind='image' ORDER BY sort,id LIMIT 4")->fetchAll();?>
<header class="hero2"><div class="h2wrap"><div class="htxt"><p class="eyebrow">The official RC rally game of Uganda</p>
<h1><?=nl2br(h(setting('hero_title',"Every driver.\nOne stage.\nRally XRC.")))?></h1><p class="lead"><?=h(setting('hero_sub','The official RC rally game of Uganda. Register your car, find your rivals and race on the dirt, from first-time juniors to veteran drivers.'))?></p>
<p><a class="btn" href="auth.php?m=register"><?=h(setting('hero_btn','Register now'))?></a> <a class="btn alt" href="#gallery">See the action</a></p><p class="small">Free to join. Juniors and Seniors welcome.</p></div>
<div class="orb"><div class="disc"></div>
<?php if($hv):?><video class="core" autoplay muted loop playsinline preload="auto" poster="<?=h($poster)?>" src="<?=h(mv($hv))?>"></video><?php else:?><img class="core" src="<?=h($bgimg)?>" alt=""><?php endif;?>
<?php foreach($circ as $k=>$c):?><figure class="fl f<?=$k+1?>"><img src="<?=h($c['path'])?>" alt="" loading="lazy"><?php if($c['caption'])echo '<figcaption>'.h($c['caption']).'</figcaption>';?></figure><?php endforeach;?>
<span class="spk s1" aria-hidden="true">&#10022;</span><span class="spk s2" aria-hidden="true">&#10022;</span></div></div></header>
<section id="news" class="wrap"><h2>Latest news</h2><?php foreach($posts as $p):?><details open><summary><?=h($p['title'])?> <small><?=h(substr($p['created'],0,10))?></small></summary><p><?=nl2br(h($p['body']))?></p></details><?php endforeach;?></section>
<section id="game" class="wrap"><h2>About the game</h2><?php foreach($db->query('SELECT * FROM articles ORDER BY sort,id LIMIT 3') as $a):?><article class="art"><?php if($a['image'])echo '<img class="ai" src="'.h($a['image']).'" alt="">';?><h3><?=h($a['title'])?></h3><p><?=h(mb_strimwidth($a['body'],0,230,'...'))?></p></article><?php endforeach;?><p class="more"><a class="btn alt" href="game.php">Read more about the game</a></p></section>
<section id="leagues" class="split"><div class="junior"><h2>Junior league</h2><p>Under 18? Bring a car, learn stage craft and race alongside friends. Mechanics and marshals are welcome too.</p><a class="btn" href="auth.php?m=register&age=Junior">Join as junior</a></div><div class="senior"><h2>Senior league</h2><p>Teams, sponsors and seasoned drivers compete for the top step. Link your team and show your livery.</p><a class="btn" href="auth.php?m=register&age=Senior">Join as senior</a></div></section>
<section id="events" class="wrap"><h2>Events</h2><div class="grid"><?php $n=0;foreach($db->query('SELECT * FROM events ORDER BY day') as $e){$n++;echo '<div class="mem"><h3>'.h($e['title']).'</h3><p>'.h($e['day']).($e['place']?', '.h($e['place']):'').'</p></div>';}if(!$n)echo '<p>No events yet. Check back soon.</p>';?></div></section>
<section id="drivers" class="wrap"><h2>The grid</h2><?php if(!$mem)echo '<p>No members yet. Be the first on the grid.</p>';?><div class="grid"><?php foreach($mem as $m):?><a class="mem" href="driver.php?id=<?=$m['id']?>"><?php $pp=photo_ok($me,$m);if($pp||!empty($m['car_photo']))echo '<span class="pics">'.($pp?'<img class="av" src="'.h($m['photo']).'" alt="">':'').(!empty($m['car_photo'])?'<img class="cv" src="'.h($m['car_photo']).'" alt="">':'').'</span>';?><h3><?=h($m['name'])?></h3><p><?=h($m['kind'])?>, <?=h($m['age_group'])?><?=$m['team']?'<br>Team: '.h($m['team']):''?><?=$m['car_type']?'<br>Car: '.h($m['car_type']):''?></p></a><?php endforeach;?></div></section>
<section id="gallery" class="wrap"><h2>Gallery</h2><div class="masonry"><?php foreach($img as $i):?><figure><img loading="lazy" src="<?=h($i['path'])?>" alt="<?=h($i['caption'])?>"><figcaption><?=h($i['caption'])?></figcaption></figure><?php endforeach;?></div><?php if($ni>count($img)):?><p class="more"><a class="btn alt" href="gallery.php#photos">More photos (<?=$ni-count($img)?> more)</a></p><?php endif;?></section>
<section id="videos" class="wrap"><h2>Videos</h2><?php if(!$vid)echo '<p>Race videos will appear here once the admin uploads them.</p>';?><div class="vgrid"><?php foreach($vid as $v):?><figure class="vid" data-src="<?=h(mv($v['path']))?>"><video muted playsinline preload="metadata" src="<?=h(mv($v['path']))?>#t=0.1"></video><figcaption><?=h($v['caption'])?></figcaption></figure><?php endforeach;?></div><?php if($nv>count($vid)):?><p class="more"><a class="btn alt" href="gallery.php#videos">More videos (<?=$nv-count($vid)?> more)</a></p><?php endif;?></section>
<script>const hv=document.querySelector('.core');if(hv&&hv.tagName=='VIDEO'&&(matchMedia('(prefers-reduced-motion:reduce)').matches||(navigator.connection&&navigator.connection.saveData))){const im=document.createElement('img');im.className='core';im.src=hv.poster;hv.replaceWith(im)}</script>
<?php foot();
