<?php require 'inc.php';$u=me();if(!$u||$u['role']!='admin'){header('Location: auth.php?m=login');exit;}
$msg='';
if($_SERVER['REQUEST_METHOD']=='POST'){chk();$a=$_POST['a']??'';$id=(int)($_POST['id']??0);
 if($a=='confirm'||$a=='reject'){$db->prepare('UPDATE deposits SET status=?,seen=1 WHERE id=?')->execute([$a=='confirm'?'confirmed':'rejected',$id]);$msg='Deposit '.($a=='confirm'?'confirmed.':'rejected.');}
 if($a=='addacc'&&trim($_POST['number']??'')){$db->prepare('INSERT INTO accounts(label,number,network) VALUES(?,?,?)')->execute([trim($_POST['label']),trim($_POST['number']),trim($_POST['network'])]);$msg='Account added.';}
 if($a=='delacc')$db->prepare('DELETE FROM accounts WHERE id=?')->execute([$id]);
 if($a=='deldep')$db->prepare('DELETE FROM deposits WHERE id=?')->execute([$id]);
 if($a=='fee'){$cl=trim($_POST['card']??'');foreach(['monthly_fee'=>(string)max(0,(int)preg_replace('/\D/','',$_POST['fee']??'')),'card_link'=>preg_match('#^https://#',$cl)?$cl:''] as $k=>$v)$db->prepare('REPLACE INTO settings(k,v) VALUES(?,?)')->execute([$k,$v]);$msg='Saved.';}}
if(isset($_GET['csv'])){header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="rallyxrc-deposits-'.date('Y-m-d').'.csv"');$o=fopen('php://output','w');fcsv($o,['Date','Member','Phone','Network','Amount UGX','Month','Reference','Status']);
 foreach($db->query('SELECT d.created,u.name,d.phone,d.network,d.amount,d.month,d.txid,d.status FROM deposits d LEFT JOIN users u ON u.id=d.user_id WHERE d.status IN (\'pending\',\'confirmed\',\'rejected\') ORDER BY d.id')->fetchAll(PDO::FETCH_NUM) as $r)fcsv($o,array_map(fn($c)=>preg_match('/^[=+\-@]/',(string)$c)?"'".$c:$c,$r));exit;}
$c=fn($q)=>$db->query($q)->fetchColumn();$T=tok();
$total=(int)$c("SELECT COALESCE(SUM(amount),0) FROM deposits WHERE status='confirmed'");$pend=(int)$c("SELECT COALESCE(SUM(amount),0) FROM deposits WHERE status='pending'");$pn=(int)$c("SELECT COUNT(*) FROM deposits WHERE status='pending'");
$mon=(int)$c("SELECT COALESCE(SUM(amount),0) FROM deposits WHERE status='confirmed' AND month='".date('Y-m')."'");$payers=(int)$c("SELECT COUNT(DISTINCT user_id) FROM deposits WHERE status='confirmed'");$new=(int)$c('SELECT COUNT(*) FROM deposits WHERE seen=0');
function f($a,$id,$T,$l,$cf=''){return '<form method="post" class="inl"'.($cf?' onsubmit="return confirm(\''.$cf.'\')"':'').'><input type="hidden" name="t" value="'.$T.'"><input type="hidden" name="a" value="'.$a.'"><input type="hidden" name="id" value="'.$id.'"><button class="'.($a=='confirm'?'btn':'x').'">'.$l.'</button></form> ';}
head('Payments | Rally XRC');?>
<main class="wrap"><h2>Payments</h2>
<?php if($msg)echo '<p class="err">'.h($msg).'</p>';if($new)echo '<p class="err">'.$new.' new deposit'.($new==1?'':'s').' since you last looked. Check each one against your mobile money messages before you confirm it.</p>';?>
<?php $on=getenv('FLW_SECRET_KEY');$wh=getenv('FLW_WEBHOOK_HASH');$pr=$_SERVER['HTTP_X_FORWARDED_PROTO']??(!empty($_SERVER['HTTPS'])?'https':'http');?>
<p class="err">Online payments: <b><?=$on?'ON':'OFF'?></b>. <?php if(!$on)echo 'Add FLW_SECRET_KEY and FLW_WEBHOOK_HASH in Railway Variables to switch them on.';else echo 'Webhook address for your Flutterwave dashboard: '.h($pr.'://'.$_SERVER['HTTP_HOST'].'/flw_webhook.php').($wh?'':' (FLW_WEBHOOK_HASH is not set yet)');?></p>
<div class="grid"><div class="mem"><b><?=ugx($total)?></b>Total confirmed</div><div class="mem"><b><?=ugx($mon)?></b>Confirmed this month</div><div class="mem"><b><?=ugx($pend)?></b><?=$pn?> pending</div><div class="mem"><b><?=$payers?></b>Members who have paid</div></div><br>
<h3>Deposits</h3><p><a class="btn alt" href="payments.php?csv=1">Download all deposits (CSV)</a></p><div class="grid">
<?php foreach($db->query("SELECT d.*,u.name FROM deposits d LEFT JOIN users u ON u.id=d.user_id WHERE d.status IN ('pending','confirmed','rejected') ORDER BY d.status='pending' DESC,d.id DESC LIMIT 200") as $d){echo '<div class="mem"><p>'.($d['seen']?'':'<b class="bd">New</b> ').'<b>'.h($d['name']).'</b><br>'.ugx($d['amount']).' for '.h($d['month']).'<br>'.h($d['network']).' '.h($d['phone']).'<br>Ref '.h($d['txid']).($d['note']?'<br>'.h($d['note']):'').'<br>'.h(substr($d['created'],0,16)).' UTC<br>Status: <b>'.h(ucfirst($d['status'])).'</b></p>'.($d['status']=='pending'?f('confirm',$d['id'],$T,'Confirm').f('reject',$d['id'],$T,'Reject'):'').f('deldep',$d['id'],$T,'Delete','Delete this deposit record?').'</div>';}?></div>
<h3>Contributions per member</h3><div class="grid"><?php foreach($db->query("SELECT u.name,u.phone,u.network,COALESCE(SUM(CASE WHEN d.status='confirmed' THEN d.amount END),0) tot FROM users u LEFT JOIN deposits d ON d.user_id=u.id WHERE u.role!='admin' GROUP BY u.id ORDER BY tot DESC") as $r)echo '<div class="mem"><p><b>'.h($r['name']).'</b><br>'.h($r['network']).' '.h($r['phone']).'<br>Contributed: <b>'.ugx($r['tot']).'</b></p></div>';?></div>
<h3>Totals per month</h3><?php foreach($db->query("SELECT month,SUM(amount) s FROM deposits WHERE status='confirmed' GROUP BY month ORDER BY month DESC") as $r)echo '<p>'.h($r['month']).': <b>'.ugx($r['s']).'</b></p>';?>
<h3>Payout accounts (for your records, members never see these)</h3><?php foreach($db->query('SELECT * FROM accounts ORDER BY id') as $r)echo '<p><b>'.h($r['number']).'</b> ('.h($r['label']).', '.h($r['network']).') '.f('delacc',$r['id'],$T,'Delete','Remove this account?').'</p>';?>
<form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="addacc"><label>Number<input name="number" required></label><label>Label (for example, Club treasurer)<input name="label"></label><label>Network<input name="network" placeholder="MTN, Airtel or both"></label><button class="btn">Add account</button></form>
<h3>Fee and card payments</h3><form method="post"><input type="hidden" name="t" value="<?=$T?>"><input type="hidden" name="a" value="fee"><label>Monthly fee (UGX, leave 0 to hide)<input name="fee" value="<?=h(setting('monthly_fee','0'))?>"></label><label>Card payment link (optional, must start with https://)<input name="card" value="<?=h(setting('card_link'))?>"></label><button class="btn">Save</button></form>
</main><?php foot();
