<?php
return [
['What is RC rally?',"Radio-controlled rally brings the drama of the real stage to a scale you can carry to the track. Drivers steer 1/10-scale cars over dirt, gravel and tarmac, chasing the fastest time rather than racing side by side. It rewards smooth driving, a good read of the surface and a car that is set up well. In Uganda, friends, families and teams meet on open ground to run their cars, share tips and cheer each other on.",'s11'],
['How a stage works',"Marshals mark the stage with chalk lines on the ground, much like the courses you can see in our photos. Each driver takes the stage alone, from the start line to the finish, with the clock running the whole way. Cutting a corner, knocking a marker or leaving the course costs time, so a clean run often beats a fast but untidy one. When every driver has run, the times are added up and the lowest total wins. Organisers explain the exact rules before each rally.",'s13'],
['The cars',"Many cars are scale copies of famous rally machines, from Subaru Imprezas and Citroen C3 WRCs to Ford Fiestas, Volkswagen Polos and Toyota GR cars. Each team dresses its car in its own livery and sponsor stickers, so you can spot a favourite from across the stage. Behind the paint, drivers and mechanics tune the suspension, choose tyres for the surface and look after the batteries and electronics. Add your car type and a photo of your car to your profile so other drivers know your machine.",'s05'],
['Juniors and Seniors',"Rally XRC welcomes two leagues. Juniors are drivers under 18 who are learning stage craft, with mechanics and marshals on hand to help. Seniors are drivers aged 18 and over who compete for the top spot. Both leagues run on the same stages and share the same spirit: respect the rules, help each other and enjoy the run. Juniors need a parent or guardian to agree before their photo is shown on the website.",'s03'],
['Safety and fair play',"Rally cars are small but fast, so a few simple habits keep everyone safe. Spectators stay behind the line and away from the stage. Drivers wait for the marshal's signal before they start. Batteries are charged in a safe place and are never left charging unattended. Everyone plays fair: no cutting the course, no arguing with marshals, and a handshake at the end of the day.",'s08'],
['How to join Rally XRC',"Joining takes a few minutes. Create your account with your mobile number, choose your league and add your team. Then open My profile to add your photo, your car photo, your car type and the driver who inspires you. Pay your monthly fee online, turn on notifications to hear about events first, and watch the news and gallery for the next rally.",'s06'],
];
